### ISSUE TITLE
What is the compiler tool chain that WasmExplorer uses? And what is the compile command?

### ISSUE THREAD

**Issue by rbgo** [mbebenita/WasmExplorer#16] opened 2017-07-13 09:26 UTC
First of all, thanks for this great app!
The "wast" code produced from C is compact and works in the browsers.
What does the compiler tool chain looks like at the service that  WasmExplorer uses and what is the compile command on the command line?

I followed the Emscripten toolchain install guide.
Should be the first go to for compiling C to WASM.
http://webassembly.org/getting-started/developers-guide/
It took +6 hours to compile and deposits 30GB on disk.
Compiling with Emscripten (emcc) the resulting .wasm file is bound to the .js/.html file and is said hard to get to run inside a browser without it.
Making a standalone .wasm with "emcc -s SIDE_MODULE=1" produces a .wasm that is a lot smaller but still twice the size of what WasmExplorer produces and crashes in browser with error.
Compiling that same snipped in WasmExplorer produces very compact wasm and works great immediately.

**Comment by yurydelendik** [comment] 2017-07-13 16:39
Mostly duplicate of https://github.com/mbebenita/WasmExplorer/issues/9

See https://github.com/wasdk/wasmexplorer-service/blob/master/scripts/compile.sh for command that compile C. Closing as answered.

**Closed by yurydelendik** 2017-07-13 16:39 UTC

**Comment by mbebenita** [comment] 2017-07-13 19:24
In summary, WasmExplorer doesn't use emscripten, it uses the wasm32 LLVM backend which I'm not sure if it is upstreamed to LLVM.

**Comment by rbgo** [comment] 2017-07-13 19:50
Yurydelendik: Sorry for the dup#9.  Thanks for giving that pointer anyway.
Mbebenita: Thanks for the wasm32 LLVM pointer.
